# Generated by Django 4.1.3 on 2022-11-22 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='is_vetted',
            new_name='is_cleared',
        ),
    ]
