# Generated by Django 4.1.3 on 2022-11-22 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit',
            name='quote',
            field=models.CharField(default='Still too and presented. Eyes workers, and a just that chosen', max_length=200),
            preserve_default=False,
        ),
    ]
