# Generated by Django 4.1.3 on 2022-11-22 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_unit_quote'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit',
            name='body',
            field=models.TextField(blank=True, null=True),
        ),
    ]
