# Generated by Django 4.1.3 on 2022-11-22 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_unit_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='unittopic',
            name='slug',
            field=models.SlugField(default='slin-suit', max_length=100, unique=True, verbose_name='Unique for URL'),
            preserve_default=False,
        ),
    ]
