# Generated by Django 4.1.3 on 2022-11-22 07:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_unittopic_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResearchLabReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('reports', models.FileField(upload_to='reports/files/')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.unit')),
            ],
        ),
        migrations.CreateModel(
            name='ExamPaper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('reports', models.FileField(upload_to='exams/files/')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.unit')),
            ],
        ),
    ]
