# Generated by Django 4.1.3 on 2022-11-22 07:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_researchlabreport_exampaper'),
    ]

    operations = [
        migrations.AddField(
            model_name='exampaper',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='exampaper',
            name='summary',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='researchlabreport',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='researchlabreport',
            name='summary',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='researchlabreport',
            name='type',
            field=models.CharField(choices=[('RP', 'Report'), ('RS', 'Research')], default='RP', max_length=3, verbose_name='Paper Type'),
        ),
    ]
