# Generated by Django 4.1.3 on 2022-11-22 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_exampaper_pub_date_exampaper_summary_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='exampaper',
            name='email',
            field=models.EmailField(default='abc@gmail.com', max_length=255, verbose_name='Email Address'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='researchlabreport',
            name='email',
            field=models.EmailField(default='abc@gmail.com', max_length=255, verbose_name='Email Address'),
            preserve_default=False,
        ),
    ]
